apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 0.22.0
  values:
    metricsServer: http://prometheus.istio-system:9090
    image:
      repository: weaveworks/flagger
      tag: 0.22.0
      pullPolicy: IfNotPresent
